### ISSUE TITLE
Highlight the important things at the top

### ISSUE THREAD

**Issue by rberge** [IHE/SNIF#3]
Github requires a login to add an issue.
The white paper is formatted such that there is a lot of information at the top that is not relevant to this particular issue.
The first thing we see could be the problem statement of what we are trying to solve but instead we see a huge IHE logo and a lot of irrelevant text. 
As a reviewer it would be best to have at the top the problem statement.   The problem statement should be short, large text and in only one or two sentences describe the problem and point to the solution. For example:
"This profile addresses the need to quickly and consistently find connectivity information for a healthcare organization's interfaces, allowing for future automation."

**Comment by JohnMoehrke** [comment]
This is the way PDF whitepapers are published by IHE.
